// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AccessToken struct {
	Token string `json:"token"`
}

type AddArticle struct {
	Title       string  `json:"title"`
	Content     string  `json:"content"`
	Image       *string `json:"image,omitempty"`
	Nooflikes   *int64  `json:"nooflikes,omitempty"`
	Noofviews   *int64  `json:"noofviews,omitempty"`
	Topic       int64   `json:"topic"`
	Author      *int64  `json:"author,omitempty"`
	Publishedat *string `json:"publishedat,omitempty"`
}

type AddTopic struct {
	Name string `json:"name"`
}

type Article struct {
	ID          *int64     `json:"id,omitempty"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	Image       *string    `json:"image,omitempty"`
	Nooflikes   *int64     `json:"nooflikes,omitempty"`
	Noofviews   *int64     `json:"noofviews,omitempty"`
	Topic       int64      `json:"topic"`
	Author      int64      `json:"author"`
	Publishedat *time.Time `json:"publishedat,omitempty"`
}

type Error struct {
	Statuscode int    `json:"statuscode"`
	Message    string `json:"message"`
}

type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterUser struct {
	Name     string  `json:"name"`
	Bio      string  `json:"bio"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Image    *string `json:"image,omitempty"`
	Isadmin  *bool   `json:"isadmin,omitempty"`
}

type Topic struct {
	ID   *int64 `json:"ID,omitempty"`
	Name string `json:"name"`
}

type UpdateArticle struct {
	ID          int64   `json:"id"`
	Title       *string `json:"title,omitempty"`
	Content     *string `json:"content,omitempty"`
	Image       *string `json:"image,omitempty"`
	Nooflikes   *int64  `json:"nooflikes,omitempty"`
	Noofviews   *int64  `json:"noofviews,omitempty"`
	Topic       *int64  `json:"topic,omitempty"`
	Publishedat *string `json:"publishedat,omitempty"`
}

type UpdateTopic struct {
	ID   int64  `json:"ID"`
	Name string `json:"name"`
}

type User struct {
	ID          *int64       `json:"id,omitempty"`
	Name        string       `json:"name"`
	Bio         string       `json:"bio"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	Image       *string      `json:"image,omitempty"`
	Isadmin     *bool        `json:"isadmin,omitempty"`
	AccessToken *AccessToken `json:"accessToken,omitempty"`
}
